DROP SCHEMA IF EXISTS 給与 CASCADE;
CREATE SCHEMA 給与;

CREATE TABLE 給与.従業員 (
    従業員ID  INTEGER PRIMARY KEY,
    登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE SEQUENCE 給与.従業員ID;

CREATE TABLE 給与.従業員の名前履歴 (
     従業員名ID INTEGER PRIMARY KEY,
     従業員ID  INTEGER NOT NULL,
     従業員名 VARCHAR(40) NOT NULL,
     登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,FOREIGN KEY (従業員ID) REFERENCES 給与.従業員(従業員ID)
);
CREATE SEQUENCE 給与.従業員名ID;

CREATE TABLE 給与.従業員の名前 (
    従業員ID  INTEGER NOT NULL,
    従業員名ID INTEGER NOT NULL,
    従業員名 VARCHAR(40) NOT NULL,
    登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (従業員ID)
    ,FOREIGN KEY (従業員ID) REFERENCES  給与.従業員(従業員ID)
    ,FOREIGN KEY (従業員名ID) REFERENCES  給与.従業員の名前履歴(従業員名ID)
);

CREATE TABLE 給与.従業員の電話番号履歴 (
    従業員電話番号ID INTEGER PRIMARY KEY,
    従業員ID  INTEGER NOT NULL,
    電話番号 VARCHAR(13) NOT NULL,
    登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,FOREIGN KEY (従業員ID) REFERENCES 給与.従業員(従業員ID)
);
CREATE SEQUENCE 給与.従業員電話番号ID;

CREATE TABLE 給与.従業員の電話番号 (
     従業員ID INTEGER NOT NULL,
     従業員電話番号ID INTEGER NOT NULL,
     電話番号 VARCHAR(13) NOT NULL,
     登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     PRIMARY KEY (従業員ID)
    ,FOREIGN KEY (従業員ID) REFERENCES  給与.従業員(従業員ID)
    ,FOREIGN KEY (従業員電話番号ID) REFERENCES  給与.従業員の電話番号履歴(従業員電話番号ID)
);

CREATE TABLE 給与.従業員のメールアドレス履歴 (
    従業員メールアドレスID INTEGER PRIMARY KEY,
    従業員ID  INTEGER NOT NULL,
    メールアドレス VARCHAR(255) NOT NULL,
    登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,FOREIGN KEY (従業員ID) REFERENCES 給与.従業員(従業員ID)
);
CREATE SEQUENCE 給与.従業員メールアドレスID;

CREATE TABLE 給与.従業員のメールアドレス (
    従業員ID  INTEGER NOT NULL,
    従業員メールアドレスID INTEGER NOT NULL,
    メールアドレス VARCHAR(255) NOT NULL,
    登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (従業員ID)
    ,FOREIGN KEY (従業員ID) REFERENCES  給与.従業員(従業員ID)
    ,FOREIGN KEY (従業員メールアドレスID) REFERENCES  給与.従業員のメールアドレス履歴(従業員メールアドレスID)
);
